version: '3.1'

services:

  torproxy:
    container_name: torproxy
    image: dperson/torproxy:latest
    environment:
      - TOR_MaxCircuitDirtiness=10
    restart: always
    ports:
      - '9050:9050'
    profiles:
      - network
      - google-poi-scraper
      - proxy

  # docker-compose --profile database up
  postgres:
    container_name: postgres
    image: kuwala/core:postgis-h3-0.2.0-alpha
    shm_size: 16g
    restart: always
    environment:
      - POSTGRES_USER=kuwala
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kuwala
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting,h3
    ports:
      - '5432:5432'
    volumes:
      - ./kuwala/tmp/kuwala/db/postgres:/var/lib/postgresql
    profiles:
      - network
      - database

  # docker-compose run database-importer --continent=<> --country=<> --country_region=<> [--population_density_date=<>]
  database-importer:
    container_name: database-importer
    image: kuwala/core:database-importer-0.2.0-alpha
    restart: always
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=kuwala
      - DATABASE_USER=kuwala
      - DATABASE_PASSWORD=password
    volumes:
      - ./kuwala/tmp/kuwala:/opt/tmp/kuwala
    profiles:
      - network

  # docker-compose run database-transformer
  database-transformer:
    container_name: database-transformer
    image: kuwala/core:database-transformer-0.2.0-alpha
    restart: always
    environment:
      - DBT_HOST=postgres
    profiles:
      - network

  # docker-compose run --service-ports jupyter
  jupyter:
    container_name: jupyter
    image: kuwala/core:jupyter-0.2.0-alpha
    restart: always
    environment: 
      - JUPYTER_ENABLE_LAB=yes
      - DBT_HOST=postgres
    volumes:
      - ./kuwala/core/jupyter/modules:/home/jovyan/kuwala/modules
      - ./kuwala/core/database/transformer:/home/jovyan/kuwala/dbt
      - ./kuwala/core/jupyter/notebooks:/home/jovyan/kuwala/notebooks
      - ./kuwala/core/jupyter/resources:/home/jovyan/kuwala/resources
      - ./kuwala/tmp/kuwala/transformer:/home/jovyan/kuwala/tmp/kuwala/transformer
    ports:
      - '8888:8888'
    profiles:
      - network
      - jupyter

  cli:
    container_name: cli
    build:
      context: kuwala
      dockerfile: ./core/cli/dockerfile
    environment:
      - DATABASE_HOST=postgres
      - JUPYTER_HOST=jupyter
    restart: always
    profiles:
      - network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/var/app/docker-compose.yml
      - ./kuwala/tmp/kuwala:/var/app/kuwala/tmp/kuwala
      - ./kuwala/core/jupyter/modules:/var/app/kuwala/core/jupyter/modules
      - ./kuwala/core/database/transformer:/var/app/kuwala/core/database/transformer
      - ./kuwala/core/jupyter/notebooks:/var/app/kuwala/core/jupyter/notebooks
      - ./kuwala/core/jupyter/resources:/var/app/kuwala/core/jupyter/resources
      - ./kuwala/tmp/kuwala/transformer:/var/app/kuwala/tmp/kuwala/transformer

  # docker-compose run admin-boundaries --continent=<> --country=<> --country_region=<>
  admin-boundaries:
    container_name: admin-boundaries
    image: kuwala/data-pipelines:admin-boundaries-0.2.0-alpha
    environment:
      - SPARK_MEMORY=16g
    volumes:
      - ./kuwala/tmp/kuwala/osm_files:/opt/tmp/kuwala/osm_files
      - ./kuwala/tmp/kuwala/admin_boundary_files:/opt/tmp/kuwala/admin_boundary_files
    restart: always
    profiles:
      - network


  # docker-compose --profile google-poi-scraper up
  google-poi-api:
    container_name: google-poi-api
    image: kuwala/data-pipelines:google-poi-api-0.2.0-alpha
    environment:
      - PROXY_ADDRESS=socks5://torproxy:9050
      - QUART_DEBUG=False
    volumes:
      - ./kuwala/pipelines/google-poi/resources/categories.json:/opt/app/pipelines/google-poi/resources/categories.json
    restart: always
    depends_on: [torproxy]
    ports:
      - '3003:3003'
    profiles:
      - network
      - google-poi-scraper

  # docker-compose run google-poi-pipeline --continent=<> --country=<> --country_region=<> --polygon_coords=<> --polygon_resolution=<> --search_string_basis=<>
  google-poi-pipeline:
    container_name: google-poi-pipeline
    image: kuwala/data-pipelines:google-poi-pipeline-0.2.0-alpha
    environment:
      - GOOGLE_POI_API_HOST=google-poi-api
      - SPARK_MEMORY=16g
    volumes:
      - ./kuwala/tmp/kuwala/google_files:/opt/app/tmp/kuwala/google_files
      - ./kuwala/tmp/kuwala/osm_files:/opt/app/tmp/kuwala/osm_files
    restart: always
    profiles:
      - network

  # docker-compose run google-trends --continent=<> --country=<> --country_region=<> --keyword=<>
  google-trends:
    container_name: google-trends
    image: kuwala/data-pipelines:google-trends-0.2.0-alpha
    environment:
      - PROXY_ADDRESS=socks5://torproxy:9050
    volumes:
      - ./kuwala/tmp/kuwala/admin_boundary_files:/opt/tmp/kuwala/admin_boundary_files
      - ./kuwala/tmp/kuwala/google_trends_files:/opt/tmp/kuwala/google_trends_files
    restart: always
    depends_on: [torproxy]
    profiles:
      - network

  # docker-compose run osm-parquetizer java -jar target/osm-parquetizer-1.0.1-SNAPSHOT.jar --continent=<> --country=<> --country_region=<>
  osm-parquetizer:
    container_name: osm-parquetizer
    image: kuwala/data-pipelines:osm-parquetizer-0.2.0-alpha
    restart: always
    volumes:
      - ./kuwala/tmp/kuwala/osm_files:/opt/app/tmp/kuwala/osm_files
    profiles:
      - network

  # docker-compose run osm-poi
  osm-poi:
    container_name: osm-poi
    image: kuwala/data-pipelines:osm-poi-0.2.0-alpha
    environment:
      - SPARK_MEMORY=16g
      - PROXY_ADDRESS=socks5://torproxy:9050
    restart: always
    depends_on: [torproxy]
    volumes:
      - ./kuwala/tmp/kuwala/osm_files:/opt/app/tmp/kuwala/osm_files
    profiles:
      - network


  # docker-compose run  population-density
  population-density:
    container_name: population-density
    image: kuwala/data-pipelines:population-density-0.2.0-alpha
    environment:
      - SPARK_MEMORY=16g
    restart: always
    volumes:
      - ./kuwala/tmp/kuwala/population_files:/opt/app/tmp/kuwala/population_files
    profiles:
      - network
