version: '3.1'

services:

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./core/database/dockerfile
    restart: always
    environment:
      - POSTGRES_USER=kuwala
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kuwala
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting,h3
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/kuwala/db/postgres/data:/var/lib/postgresql/data
    profiles:
      - network
      - database

  jupyter:
    container_name: jupyter
    build:
      context: .
      dockerfile: ./core/jupyter/docker/dockerfile
    restart: always
    environment: 
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./common/jupyter/modules:/home/jovyan/kuwala/modules
      - ./common/jupyter/notebooks:/home/jovyan/kuwala/notebooks
      - ./common/jupyter/resources:/home/jovyan/kuwala/resources
    ports:
      - '8888:8888'
    profiles:
      - network

  torproxy:
    container_name: torproxy
    image: dperson/torproxy:latest
    environment: 
      - TOR_MaxCircuitDirtiness=10
    restart: always
    ports:
      - '9050:9050'
    profiles:
      - network
      - google-poi-scraper
      - proxy

  # docker-compose run admin-boundaries --continent=<> --country=<> --country_region=<>
  admin-boundaries:
    container_name: admin-boundaries
    environment:
      - SPARK_MEMORY=16g
    build:
      context: .
      dockerfile: ./pipelines/admin-boundaries/dockerfile
    volumes:
      - ./tmp/kuwala/osmFiles:/opt/tmp/kuwala/osmFiles
      - ./tmp/kuwala/adminBoundaries:/opt/pipelines/app/tmp
    restart: always
    profiles:
      - network


  # docker-compose --profile google-poi-scraper up
  google-poi-api:
    container_name: google-poi-api
    environment:
      - PROXY_ADDRESS=socks5://torproxy:9050
      - QUART_DEBUG=False
    build:
      context: .
      dockerfile: ./pipelines/google-poi/dockerfile
    restart: always
    depends_on: [torproxy]
    ports:
      - '3003:3003'
    profiles:
      - network
      - google-poi-scraper

  # docker-compose run google-poi-pipeline
  google-poi-pipeline:
    container_name: google-poi-pipeline
    environment:
      - GOOGLE_POI_API_HOST=google-poi-api
      - SPARK_MEMORY=16g
    build:
      context: .
      dockerfile: ./pipelines/google-poi/src/pipeline/dockerfile
    volumes:
      - ./tmp/kuwala/google_files:/opt/app/tmp/kuwala/google_files
      - ./tmp/kuwala/osm_files:/opt/app/tmp/kuwala/osm_files
    restart: always
    profiles:
      - network

  # docker-compose run osm-parquetizer java -jar target/osm-parquetizer-1.0.1-SNAPSHOT.jar <pbf-path> <parquet-path>
  osm-parquetizer:
    container_name: osm-parquetizer
    build:
      context: .
      dockerfile: ./pipelines/osm-poi/osm-parquetizer/dockerfile
    restart: always
    volumes:
      - ./tmp/kuwala/osm_files:/opt/app/tmp/kuwala/osm_files
    profiles:
      - network

  # docker-compose run osm-poi
  osm-poi:
    container_name: osm-poi
    build:
      context: .
      dockerfile: ./pipelines/osm-poi/dockerfile
    environment:
      - SPARK_MEMORY=16g
      - PROXY_ADDRESS=socks5://torproxy:9050
    restart: always
    depends_on: [torproxy]
    volumes:
      - ./tmp/kuwala/osm_files:/opt/app/tmp/kuwala/osm_files
    profiles:
      - network


  # docker-compose run  population-density
  population-density:
    container_name: population-density
    build:
      context: .
      dockerfile: ./pipelines/population-density/dockerfile
    environment:
      - SPARK_MEMORY=16g
    restart: always
    volumes:
      - ./tmp/kuwala/population_files:/opt/app/tmp/kuwala/population_files
    profiles:
      - network
