version: '3.1'

services:

  neo4j:
    container_name: neo4j
    build:
      context: .
      dockerfile: ./core/neo4j/docker/dockerfile
    restart: always
    environment: 
      - NEO4J_AUTH=none
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=3G
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./tmp/kuwala/db/neo4j/data:/data
    profiles:
      - core
      - network

  jupyter:
    container_name: jupyter
    build:
      context: .
      dockerfile: ./core/jupyter/docker/dockerfile
    restart: always
    environment: 
      - NEO4J_HOST=bolt://neo4j:7687
    ports:
      - '8888:8888'
    profiles:
      - core
      - network

  torproxy:
    container_name: kuwala-pipelines_torproxy
    image: dperson/torproxy:latest
    environment: 
      - TOR_MaxCircuitDirtiness=10
    restart: always
    ports:
      - '9050:9050'
    profiles:
      - network
      - google-poi-scraper

  # docker-compose --profile google-poi-scraper up
  google-poi-api:
    container_name: google-poi-api
    environment:
      - PROXY_ADDRESS=socks5://kuwala-pipelines_torproxy:9050
      - QUART_DEBUG=False
    build:
      context: .
      dockerfile: ./pipelines/google-poi/dockerfile
    restart: always
    depends_on: [torproxy]
    ports:
      - '3003:3003'
    profiles:
      - network
      - google-poi-scraper

  # docker-compose run google-poi-pipeline
  google-poi-pipeline:
    container_name: google-poi-pipeline
    environment:
      - MONGO_HOST=kuwala-pipelines_mongo_db
      - GOOGLE_POI_API_HOST=google-poi-api
    build:
      context: .
      dockerfile: ./pipelines/google-poi/src/pipeline/dockerfile
    volumes:
      - ./tmp/kuwala/googleFiles:/opt/pipeline/tmp/googleFiles
    restart: always
    profiles:
      - network

  # docker-compose run neo4j-importer
  neo4j-importer:
    environment: 
      - NEO4J_HOST=bolt://neo4j:7687
      - MONGO_HOST=kuwala-pipelines_mongo_db
    build:
      context: .
      dockerfile: ./core/neo4j/importer/dockerfile
    volumes:
      - ./tmp/kuwala:/opt/app/tmp/kuwala
    restart: always
    depends_on: [neo4j]
    profiles:
      - network

  # docker-compose run osm-parquetizer java -jar target/osm-parquetizer-1.0.1-SNAPSHOT.jar <pbf-path> <parquet-path>
  osm-parquetizer:
    build:
      context: .
      dockerfile: ./pipelines/osm-poi/osm-parquetizer/dockerfile
    restart: always
    volumes:
      - ./tmp/kuwala/osmFiles:/opt/app/tmp/osmFiles
    profiles:
      - network

  # docker-compose run osm-poi
  osm-poi:
    build:
      context: .
      dockerfile: ./pipelines/osm-poi/dockerfile
    restart: always
    volumes:
      - ./tmp/kuwala/osmFiles:/opt/app/tmp/osmFiles
    profiles:
      - network


  # docker-compose run  population-density
  population-density:
    build:
      context: .
      dockerfile: ./pipelines/population-density/dockerfile
    restart: always
    volumes:
      - ./tmp/kuwala/populationFiles:/opt/app/tmp/populationFiles
    profiles:
      - network
